In [44]:
import numpy as np
list = [1,2,3,4]
arr = np.array(list)
print(arr)
arr.shape

[1 2 3 4]


(4,)

In [20]:
list1= [2,4,6,7,8,5]
list2= [1,2,3,4,5,4]
list3= [2,5,6,7,9,8]
list4= [1,5,9,8,7,5]
arr= np.array([list1,list2,list3,list4])
arr[1:, 2:5]

array([[3, 4, 5],
       [6, 7, 9],
       [9, 8, 7]])

In [49]:
arr = np.arange(0,10,step=1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.linspace(0,1,num=5,endpoint =False)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [56]:
print(arr)
arr1 = arr.copy()
arr1[1:4] = 500
arr1

[  0   1   2 300 300 300 300 300 300 300]


array([  0, 500, 500, 500, 300, 300, 300, 300, 300, 300])

In [59]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [72]:
np.random.rand(3,5)

array([[0.53394936, 0.89029799, 0.65439333, 0.60328179, 0.32367102],
       [0.17019809, 0.85048822, 0.55588218, 0.49651929, 0.18983561],
       [0.84339406, 0.08369891, 0.87499921, 0.87089309, 0.70778011]])

In [71]:
np.random.randn(3,3)

array([[-0.39553969,  0.6296803 , -0.45788445],
       [-0.19415487, -1.30780128, -1.2124134 ],
       [-1.16176711, -1.37402862,  0.37631115]])

In [81]:
np.random.randint(0,5,size=None)

0

In [83]:
np.random.random_sample((2,3))

array([[0.99299335, 0.63817791, 0.15812599],
       [0.61823199, 0.18357405, 0.28164356]])

In [9]:
 v = np.arange(5)
print(f'A numpy vector {v} with shape {v.shape}')
print(f'Transpose of numpy vector {v.T} with shape {v.T.shape}')
V = v.reshape(-1, 1)
print(f'A matrix with shape {V.shape}:\n{V}')
print(f'A transposed matrix with shape {V.T.shape}:\n{V.T}')

<IPython.core.display.Javascript object>

A numpy vector [0 1 2 3 4] with shape (5,)
Transpose of numpy vector [0 1 2 3 4] with shape (5,)
A matrix with shape (5, 1):
[[0]
 [1]
 [2]
 [3]
 [4]]
A transposed matrix with shape (1, 5):
[[0 1 2 3 4]]


In [10]:
v

array([0, 1, 2, 3, 4])

In [11]:
V = v.reshape(-1, 1)
V

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [12]:
V*v

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])

In [4]:
a =np.arange(5)
a

<IPython.core.display.Javascript object>

array([0, 1, 2, 3, 4])

In [6]:
b = a.reshape(-1, 1)
b

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [7]:
a*b

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])